EZP-31642: As an Editor I want be able to edit table borders
ezsystems/ezplatform-richtext pull request #151
Opened 2020-05-20 14:57 UTC by SerheyDolgushev

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31642](https://jira.ez.no/browse/EZP-31642)
| **Bug/Improvement**| yes
| **New feature**    | yes
| **Target version** | 2.0
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This PR provides a new concept for custom attributes in Online Editor. In some cases, there is no need to use data attributes for them. Table border is a great example, and I guess there might be more cases.

Steps to test it:
1. Just add `border` custom attribute for tables:
    ```
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    attributes:
                        table:
                            border: { type: number, default_value: 1 }
    ```

2. Open Online Editor and insert the table

3. Using elements path (at the bottom of the Online Editor) select a table

4. Click "Edit" icon in the table toolbar

Please note this PR depends on https://github.com/ezsystems/ezplatform-richtext/pull/150, and without schema changes, table-border edits won't be saved in the database. But it is still possible to test UI without that PR.

And some JavaScript improvement suggestions are expected here :)

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2020-09-23 09:03 UTC, dew326 requested changes

2020-09-23 09:03 UTC, dew326 commented on src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-attributes-edit.js
> +            table: ['border']
I don't like to have this hardcoded here. 
I think it should be in the `eZ.richText` config.

2020-09-23 09:03 UTC, dew326 commented on src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-attributes-edit.js
> -
Please do not remove this line. This improves readability.

2020-09-23 09:03 UTC, dew326 commented on src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-attributes-edit.js
> +
```suggestion
```

2020-09-23 19:26 UTC, SerheyDolgushev commented
@dew326 please check all the requested changes in https://github.com/ezsystems/ezplatform-richtext/pull/151/commits/e57e930945b20223b4aa67f9792a694eef9d0a9e

2020-09-24 09:30 UTC, dew326 approved these changes
+1 for the frontend part

2020-09-24 11:24 UTC, GrabowskiM approved these changes

2020-09-24 13:57 UTC, lucasOsti approved these changes

2020-09-30 06:24 UTC, micszo commented
@SerheyDolgushev I believe this should be rebased against 2.1, v3.0 reached EOL in August. (and in fact v3.1 will be past EOM tomorrow, https://support.ibexa.co/Public/Service-Life#)

2020-09-30 12:40 UTC, SerheyDolgushev commented
@micszo rebased onto `2.1`.

2020-10-02 08:51 UTC, katarzynazawada approved these changes
Tested together with https://github.com/ezsystems/ezplatform-richtext/pull/150

2020-10-02 08:52 UTC, merged

2020-10-02 08:53 UTC, lserwatka commented
@alongosz could you merge it up?

2020-10-02 09:04 UTC, alongosz commented
Merged up #150 and #151 to master via e2bdfdc47.

2020-10-02 09:04 UTC, alongosz commented
Thank you @SerheyDolgushev :tada: