EZP-31954: add missed validation error target
ezsystems/ezplatform-richtext pull request #164
Opened 2020-09-25 09:41 UTC by ITernovtsiy

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31954](https://jira.ez.no/browse/EZP-31954)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 1.0
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This is a part of issue with RichText XML validation fails,  where fatal error displayed:
{noformat}
Argument 2 passed to Symfony\Component\Validator\Util\PropertyPath::append() must be of the type string, null given, called in /app/vendor/ezsystems/ezplatform-content-forms/src/lib/Validator/Constraints/FieldValueValidator.php on line 92 [in vendor/symfony/validator/Util/PropertyPath.php:34]
{noformat}
see https://github.com/ezsystems/ezplatform-content-forms/pull/34
I see similar is done for Float field type
https://github.com/ezsystems/ezpublish-kernel/blob/7.5/eZ/Publish/Core/FieldType/Float/Type.php#L125

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2020-10-05 11:56 UTC, adamwojs commented
Hi @ITernovtsiy! 

Thank you for submitting PR. Q: Are unit tests failing here because of missing ezsystems/ezplatform-content-forms#34 changes?

2020-10-05 12:30 UTC, alongosz requested changes

2020-10-06 14:09 UTC, bogusez approved these changes

2020-10-06 14:10 UTC, merged

2020-10-06 14:10 UTC, lserwatka commented
@alongosz could you merge it up?

2020-10-06 22:06 UTC, alongosz commented
Merged up to master via bfebb27c0.