EZP-32376: As an Editor, I want to see elements path
ezsystems/ezplatform-richtext pull request #179
Opened 2021-03-05 09:27 UTC by dew326

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-32376](https://jira.ez.no/browse/EZP-32376)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | master
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Ask for Code Review.

2021-03-05 13:59 UTC, lucasOsti approved these changes

2021-03-08 10:08 UTC, GrabowskiM requested changes

2021-03-08 10:08 UTC, GrabowskiM commented on src/bundle/Resources/public/js/CKEditor/plugins/elements-path.js
> +            this.elementsPathWrapper = this.editor.sourceElement.parentElement.querySelector('.ez-elements-path');
getter setting value? Nope nope nope, do it in constructor, didMount or sth like this

2021-03-08 11:28 UTC, GrabowskiM approved these changes

2021-03-08 11:33 UTC, merged