IBX-707: Improved RichTextConverterExtension libxml-related error handling
ezsystems/ezplatform-richtext pull request #194
Opened 2021-07-05 15:00 UTC by konradoboza

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-707](https://issues.ibexa.co/browse/IBX-707)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `2.3`, `master`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Given `saveHTML` method might return false in case of external errors/libxml flaws, we should introduce more bulletproof checks for returned values. Error logging doesn't seem to be needed, as the converter will throw an exception in case of any libxml errors anyway, ref: https://github.com/ezsystems/ezplatform-richtext/blob/68e21b4be1477c09bb1a5cf0e2a9fae648a42b69/src/lib/eZ/RichText/Converter/Xslt.php#L140

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2021-07-05 18:30 UTC, adamwojs approved these changes

2021-07-06 07:23 UTC, mateuszdebinski approved these changes

2021-07-06 07:25 UTC, Steveb-p approved these changes
Does it make sense to have tests for these?

There's also the possibility of changing the `saveHTML` method to always return `string` on it's own, but I guess there's value in it returining `false` in some cases? (despite the possible exceptions).

2021-07-06 07:28 UTC, mateuszdebinski commented
we have a lot of places that call richtext convert and save HTML, shouldn't we introduce this everywhere (where it needs to be, of course)? for example in: `ezsystems/ezplatform-page-fieldtype/src/lib/GraphQL/Resolver/RichtextBlockAttributeTypeResolver.php`?

2021-07-06 07:28 UTC, adamwojs commented
> There's also the possibility of changing the saveHTML method to always return string on it's own, but I guess there's value in it returining false in some cases? (despite the possible exceptions).

Yes, but this will require contribution to https://github.com/php/php-src. It's https://www.php.net/manual/en/domdocument.savehtml.php :wink:

2021-07-06 07:39 UTC, konradoboza commented
@mateuszdebinski I think this could be indeed introduced in other repositories but in methods that directly use `string` as a type-hint. WDYT @adamwojs @alongosz?

2021-07-06 08:17 UTC, Steveb-p commented
> > There's also the possibility of changing the saveHTML method to always return string on it's own, but I guess there's value in it returining false in some cases? (despite the possible exceptions).
> 
> Yes, but this will require contribution to https://github.com/php/php-src. It's https://www.php.net/manual/en/domdocument.savehtml.php

I assumed we wrap it with our own class (since I've noticed we're using our own interface).

2021-07-06 09:51 UTC, alongosz requested changes
1. Missing test coverage
2. Missing logging of an error. It might be more clear how to log this if we have 1.

2021-07-06 09:56 UTC, Steveb-p commented
> 2\. Missing logging of an error. It might be more clear how to log this if we have 1.

@konradoboza it can be done easily by using `LoggerAwareInterface` and `LoggerAwareTrait` btw.

see https://symfony.com/doc/current/logging.html#using-a-logger-inside-a-service

2021-07-06 10:17 UTC, patrickallaert commented
> There's also the possibility of changing the `saveHTML` method to always return `string` on it's own, but I guess there's value in it returining `false` in some cases? (despite the possible exceptions).

Not going to happen any time soon (the earliest would be PHP 9.0) because of serious BC break.
A `false` being returned really denotes something wrong happened (unless you distribution provides you libxml2 2.9.12 without a patch for https://gitlab.gnome.org/GNOME/libxml2/-/issues/266 when you try converting an empty DOM to HTML).

2021-07-07 18:50 UTC, patrickallaert commented
> 1. Missing test coverage

This might be very tricky to get as it requires a buggy version of libxml2 that would enables PHP's `DOMDocument->saveHTML()` to return `false`.

2021-07-08 08:09 UTC, alongosz commented
> > 1. Missing test coverage
> 
> This might be very tricky to get as it requires a buggy version of libxml2 that would enables PHP's `DOMDocument->saveHTML()` to return `false`.

@patrickallaert I was rather thinking of loading erroneous document that would return that. Since the behavior is documented I assumed there are specific cases when it would happen apart from buggy libxml version.

2021-07-12 11:39 UTC, alongosz approved these changes
After internal sync with @konradoboza looks like we've expired possibilities of making proper logging & coverage and looks like the erroneous state is related indeed only to specific libxml version(s)

Hence, +1

2021-07-13 10:59 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 3.3.6 & 3.3.6-dev with patch & diff.

2021-07-13 12:01 UTC, merged