IBX-769: Extensibility for Online Editor
ezsystems/ezplatform-richtext pull request #203
Opened 2021-08-18 14:08 UTC by damianz5

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-769](https://issues.ibexa.co/browse/IBX-769)
| **Improvement**| yes
| **New feature**    | yes
| **Target version** | master
| **BC breaks**      | no
| **Tests pass**     | no
| **Doc needed**     | yes

Extensibility for Online Editor:
- Changing the order of the buttons
- Disabling some buttons
- Compatible with Custom plugins

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2021-09-01 08:05 UTC, Steveb-p commented on src/lib/Configuration/Provider/CKEditor.php
> +     * @return string[] List of visible buttons
Phpdoc does not match it's usage.

2021-09-01 09:47 UTC, Steveb-p requested changes
PR description declares that this does not introduce BC breaks. Can you confirm that users having previous configuration variant can safely upgrade without changing it?

What about existing editor extensions? Do they need to be updated?

I see that this goes into `master` branch, but if it introduces BC breaks in any way, then they should be documented and an upgrade path has to be provided.

2021-09-01 09:47 UTC, Steveb-p commented on src/lib/Configuration/Provider/CKEditor.php
> +        array_pop($toolbars);
I believe a comment explaining the purpose of this operation is in order here.

2021-09-01 09:47 UTC, Steveb-p commented on tests/lib/Configuration/Provider/CKEditorTest.php
> +            ->expects($this->any())
This does not do anything.
```suggestion
```

2021-09-01 09:47 UTC, Steveb-p commented on tests/lib/Configuration/Provider/CKEditorTest.php
> +class CKEditorTest extends BaseProviderTestCase
```suggestion
final class CKEditorTest extends BaseProviderTestCase
```

2021-09-24 10:58 UTC, alongosz commented
@damianz5 I feel like both JIRA issue and the title is to vague. Is this about extensibility of toolbar buttons or something more? Specifically what does it mean "Compatible with Custom plugins"?

2021-09-24 11:58 UTC, damianz5 commented
PR description updated

2021-10-04 07:36 UTC, Steveb-p approved these changes
Looks ok for me, although I'm not a fan of prefixing calls to global functions with `\`. Performance improvement is negligible (especially with OPCache).

2021-10-04 07:45 UTC, ViniTou approved these changes

2021-10-04 08:17 UTC, alongosz approved these changes

2021-10-04 08:17 UTC, alongosz commented on tests/lib/Configuration/Provider/CKEditorTest.php
> +            ->expects($this->exactly(1))
It's static, so should be called with `self::` and there's more specific method to achieve the same:
```suggestion
            ->expects(self::once())
```

2021-10-04 09:33 UTC, adamwojs approved these changes

2021-10-04 09:33 UTC, adamwojs commented on src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
> +            ->arrayNode(self::TOOLBAR_NODE_KEY)
This BC break needs to be mentioned in upgrade notes @ezsystems/documentation-team

2021-10-13 05:10 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 4.0.0-dev.

2021-10-13 07:36 UTC, merged